### ISSUE TITLE
Permission for "/join"

### ISSUE THREAD

**Issue by GaetanOff** [Swisscypher/smartqueue#1]
Hi,
Can you add a permission for the "/join" please ?

I don't want my players to be able to join a server via the "/join" but only via the API.
Cuz this can broke my auth plugin or my 2fa plugin, because I cannot cancel a bungee command via spigot.

Thanks 👍🏼

**Comment by Zayceur** [comment]
Done in 000c95714771bf535549d866361dbff35fc650b9
