### ISSUE TITLE
Queue stuck when server restart

### ISSUE THREAD

**Issue by Fantaster142** [Swisscypher/smartqueue#3]
Hello, i have a little bug with queue :

When a server is restarting and a player is trying to join the queue to acess it, the queue for this server only get stuck (/unstuck queue don't work) and nobody can join the server even if the server is started or not.
I need to restart the bungee to unstuck the queue.

Hope you can help me with this, Thanks.

**Comment by ElFamosoComore** [comment]
Hello !

May I ask you the content of your `config.yml` file, and the version of BungeeCord AND SmartQueue you're using ?

**Comment by Fantaster142** [comment]
Here's my config.yml : https://paste.gg/p/anonymous/96c190c12a5c46b6a9733018011dcf59
I'm using SmartQueue 1.1.10 And i am usin FlameCord version 0.6.2

**Comment by Zayceur** [comment]
Hello @Fantaster142,

We tested SmartQueue 1.1.10 on FlameCord 0.6.3 (the latest) and 0.6.2 (your version) and sadly we can't replicate the bug.

Are you sure your spigot server was 100% ready ?
Did you try to do `/server faction` to check if it was really online ?
Did you do `/unstuck faction` ? (as I think it was the faction server you tried to restart)

Thanks for your answers !

**Comment by Fantaster142** [comment]
Hello, i was able to join the server with /server faction so the server was well launched and I did the command /unstuck faction.
I use the JPremium plugin maybe it has something to do with the bug.

I will do more testing on my side.

**Comment by ElFamosoComore** [comment]
Hello !

We haven't heard about you for 4 days, is the problem still occurring ? Have you found anything relevant during your tests ?

Thank you in advance for your answer.

**Comment by ElFamosoComore** [comment]
Hello, we fixed your problem in a6a6617.

Please check [v1.1.12](https://github.com/Swisscypher/smartqueue/releases/tag/v1.1.12). If the problem persists, let us know in this issue.
